### ISSUE TITLE
Obj-C Sample Code?

### ISSUE THREAD

**Issue by bassrock** [creitz/CRDropdownAlert#1]
I was wondering if there is any Obj-C sample code or setup instructions. I am trying to slowly convert an old project and need to use bits of Swift and Obj-C and can't get the class methods to work in Obj-C

**Comment by creitz** [comment]
Hi there. I apologize for the (incredibly) delayed response. For some reason I didn't get a notification for this and just happened to stumble on this issue. I haven't written any objective c in some time now, but if you're still having issues feel free to share your code and I can try to help out.
